# Reference: https://docs.ansible.com/ansible/latest/collections/community/general/mail_module.html
- name: "Send website policies"
  hosts: all
  tasks:

    #* Mail credentials retrieving
    - name: "Call bahul"
      ansible.builtin.uri:
        url: https://bahul.yuki.es/api/MailUser
        method: GET
        headers:
          x-token: "{{ token }}"
      register: "mailuser"
      delegate_to: localhost

    #* Send email thorugh gmail
    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ mailuser.json.body.user }}"
        password: "{{ mailuser.json.body.pass }}"
        to: "{{ destinatario }}"
        subject: Comunicación de políticas {{ Empresa }}
        subtype: html
        body: '<h1>Change log</h1>'
      delegate_to: localhost

    #* Notification
    - name: "Send notification"
      ansible.builtin.uri:
        url: https://chat.googleapis.com/v1/spaces/AAAAlCHjbao/messages?key=...
        method: POST
        headers:
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body:
          text: "*Executed on:* {{ ansible_hostname }}\n*Playbook executed:* {{ ansible_play_name }}\n"
      delegate_to: localhost
