# Reference: https://docs.ansible.com/ansible/latest/collections/community/general/mail_module.html
- name: "Send staff policies periodically"
  hosts: all
  tasks:

    #* Mail credentials retrieving
    - name: "Call bahul"
      ansible.builtin.uri:
        url: https://bahul.yuki.es/api/MailUser
        method: GET
        headers:
          x-token: "{{ token }}"
      register: "mailuser"
      delegate_to: localhost

    #* Send email thorugh gmail
    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ mailuser.json.body.user }}"
        password: "{{ mailuser.json.body.pass }}"
        to: "{{ destinatario }}"
        subject: Recordatorio de políticas y normas YukiInc
        subtype: html
        body: '<p>Buenos días equipo,</p> <p>debido a la implementación de los sistemas de gestión de la información es nuestra obligación informaros de todas las responsabilidades relacionadas con dicha implementación que os afectan directa o indirectamente.</p><p>Normas de uso: <a href="{{ enlace }}">NS-SGSI Normas de Uso</a></p><p><b>Procedimientos de operaciones</b></p><p>Cualquier petición entre departamentos debe ser realizada por medio de una petición formal utilizando nuestra herramienta de trabajo Jira por motivos de auditoria, entre ellos desbloqueos de usuarios, restablecimientos de contraseñas o semejantes.</p><p><b>Utilización de recursos de YukiInc</b></p><p>Se recuerda a los empleados que cualquier uso inadecuado de nuestros recursos tales sean, la utilización de la red para actividades que no estén estrictamente relacionadas con el trabajo o exfiltración de información, repositorios o documentación, quedan expresamente prohibidos.</p><p><b>Auditorias</b></p><p>Los recursos de YukiInc serán auditados con tal de favorecer el correcto funcionamiento de los procesos productivos de YukiInc. Quedarán registros de toda interacción con servidores y dispositivos de red.</p><p>Un saludo</p>'
        attach:
        - /tmp/incibe/27001-NS-SGSINormasdeUso.pdf
      delegate_to: localhost


    #* Notification
    # - name: "Send notification"
    #   ansible.builtin.uri:
    #     url: https://chat.googleapis.com/v1/spaces/AAAAlCHjbao/messages?key=...
    #     method: POST
    #     headers:
    #       Content-Type: "application/json; charset=UTF-8"
    #     body_format: json
    #     body:
    #       text: "*Executed on:* {{ ansible_hostname }}\n*Playbook executed:* {{ ansible_play_name }}\n"
    #   delegate_to: localhost

