---
- hosts: all
  serial: 1
  gather_facts: no
  tasks:
    - name: Restarting the Spooler service...
      win_service:
        name: spooler
        state: restarted
      register: service_info