- name: "Descargar último Backup CIM"
  hosts: all
  tasks:  
    # - name: Create a mapped drive under Z
    #   community.windows.win_mapped_drive:
    #     letter: Z
    #     path: \\intrinas01\Copias\CIM_Copy
    - name: "Ejecutar script"
      ansible.windows.win_powershell:
        script: |
          C:\apps\Scripts\Task_CIM_backups_FTP.ps1