---
- name: "Windows hosts áctivos y configurados"  
  gather_facts: no   
  connection: local
  hosts: windows
  tasks:

  - name: "Comprobar si el host remoto tiene el puerto de winrm abierto"
    shell: if nc -zvw10 {{ inventory_hostname }} 5986 > /dev/null ;then echo "True"; else echo "False"; fi
    delegate_to: localhost
    register: check

  - name: "Cambia el tipo de conexión que utilizará a winrm"
    when: check.stdout_lines[0] == "True"
    set_fact:
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_server_cert_validation: "ignore"
      ansible_become_method: "runas"
      ansible_winrm_transport: "ntlm"

  - name: "Instala las actualizaciones"
    when: check.stdout_lines[0] == "True"
    register: update_result
    ansible.windows.win_updates:
      category_names: ['SecurityUpdates''CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
  
  - name: "Reinicia el host si es necesario"
    when: check.stdout_lines[0] == "True"
    block:
      - name: "Envía notificación al chat"
        ansible.windows.win_shell: |
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]" # Creamos diccionario de powershell para el header
          $headers.Add("Content-Type", "application/json; charset=utf-8")  # Agregamos el content-type

          # Definimos el texto del mensaje que queramos
          $body = '{
              "text": "*Executed on:* {{ ansible_hostname }}\n*Playbook executed:* {{ ansible_play_name }}"
          }'

          # Envía el contenido del mensaje al webhook
          Invoke-RestMethod 'https://chat.googleapis.com/v1/spaces/AAAAlCHjbao/messages?key=...' -Method 'POST' -Headers $headers -Body $body
      
      - name: "Reinicia el host y espera 6 min"
        ansible.windows.win_reboot:
          reboot_timeout: 3600

    rescue: # Si algo peta arriba nos lo comunica sin marcar el failed en semaphore
      - debug: msg="No ha sido posible en {{ ansible_hostname }}"