- name: Cambiar docker compose -> docker-compose v2
  hosts: all
  vars: 
    ip: 192.168.1.254
  tasks:
    - name: Comprobamos que existe docker
      ansible.windows.win_shell: docker compose

    - name: Descargar script de mi maquina por http
      when: output is succeeded
      get_url:
        url: http://{{ ip }}:8000/App_ChangeDocker-compose.ps1
        dest: c:\apps\scripts

    - name: Ejecutamos script
      ansible.windows.win_shell: c:\apps\scripts\App_ChangeDocker-compose.ps1