---
- hosts: all
  become: yes
  become_method: su
  become_user: root
  strategy: free
  tasks:
  
  - name: Update repositories cache and install "mount" package
    apt:
      name: 
        - mount
        - curl
      update_cache: yes
  
  - name: Disabling Swap on all nodes
    shell: /sbin/swapoff -a
    args:
      executable: /bin/bash
  
  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'
  
  - name: Add IPs to /etc/hosts on master and workers
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}"
      state: present
    when: hostvars[item].ansible_ssh_host is defined
    with_items: "{{ ansible_play_batch }}"