- name: "Set up Zookepers"
  hosts: all
  vars:
    version: 3.8.3
  tasks:
    - name: "Apt update and install packages"
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - zip
        - net-tools
        - vim
        - nano
        - tar
        - netcat
        - openjdk-8-jdk
    
    - name: "Disable swappiness"
      shell: |
        sysctl vm.swappiness=1
        echo 'vm.swappiness=1' | sudo tee --append /etc/sysctl.conf

    - name: "Create zookeper user"
      user:
        name: zookeper
        shell: /usr/sbin/nologin

    - name: "Download zookeper and kafka"
      shell: |
        wget https://dlcdn.apache.org/zookeeper/zookeeper-{{ version }}/apache-zookeeper-{{ version }}-bin.tar.gz
        tar -xvf apache-zookeeper-{{ version }}-bin.tar.gz
        rm apache-zookeeper-{{ version }}-bin.tar.gz
        mv apache-zookeeper-{{ version }}-bin /opt/zookeper
    
    - name: "Set up zookeper folder permissions"
      file:
        path: /opt/zookeper
        state: directory
        owner: zookeper
        group: zookeper
        recurse: yes
    
    - name: "Create data zookeper folder"
      file:
        path: /var/zookeeper
        state: directory
        owner: zookeper
        group: zookeper
        recurse: yes
    
    - name: "Zookeper properties"
      copy:
        src: "{{ playbook_dir }}/conf/zookeper/zookeper.properties"
        dest: /opt/zookeper/conf/zoo.cfg
        owner: zookeper
        group: zookeper
        mode: '0644'

    
    - name: "Configure systemd service"
      copy:
        src: "{{ playbook_dir }}/conf/systemd/zookeper.service"
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0644'
    
    - name: "Configure systemd service"
      copy:
        src: ./conf/systemd/zookeper.service
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0644'

    - name: "systemctl daemon-reload"
      shell: systemctl daemon-reload

# latest kafka version
# wget https://downloads.apache.org/kafka/3.6.0/kafka_2.12-3.6.0.tgz