- name: "Set up Zookepers"
  hosts: all
  vars:
    version: 3.8.3
  tasks:
    - name: "Apt update and install packages"
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - zip
        - net-tools
        - vim
        - nano
        - tar
        - netcat
        - openjdk-8-jdk
    
    - name: "Disable swappiness"
      shell: |
        sysctl vm.swappiness=1
        echo 'vm.swappiness=1' | sudo tee --append /etc/sysctl.conf

    - name: "Create zookeper user"
      user:
        name: zookeper
        shell: /usr/sbin/nologin

    - name: "Download zookeper and kafka"
      ignore_errors: true
      shell: |
        wget https://dlcdn.apache.org/zookeeper/zookeeper-{{ version }}/apache-zookeeper-{{ version }}-bin.tar.gz
        tar -xvf apache-zookeeper-{{ version }}-bin.tar.gz
        rm apache-zookeeper-{{ version }}-bin.tar.gz
        mv -f apache-zookeeper-{{ version }}-bin zookeper
        mv -f zookeeper /opt/
    
    - name: "Set up zookeper folder permissions"
      file:
        path: /opt/zookeper
        state: directory
        owner: zookeper
        group: zookeper
        recurse: yes
    
    - name: "Create data zookeper folder"
      file:
        path: /var/zookeeper
        state: directory
        owner: zookeper
        group: zookeper
        recurse: yes
    
    - name: "Zookeper properties"
      copy:
        # src: "{{ playbook_dir }}/conf/zookeper/zookeper.properties"
        dest: /opt/zookeper/conf/zoo.cfg
        owner: zookeper
        group: zookeper
        mode: '0644'
        content: |
          # the location to store the in-memory database snapshots and, unless specified otherwise, the transaction log of updates to the database.
          dataDir=/var/zookeeper
          # the port at which the clients will connect
          clientPort=2181
          # disable the per-ip limit on the number of connections since this is a non-production config
          maxClientCnxns=0
          # the basic time unit in milliseconds used by ZooKeeper. It is used to do heartbeats and the minimum session timeout will be twice the tickTime.
          tickTime=2000
          # The number of ticks that the initial synchronization phase can take
          initLimit=10
          # The number of ticks that can pass between
          # sending a request and getting an acknowledgement
          syncLimit=5
          # zoo servers
          # these hostnames such as `zookeeper-1` come from the /etc/hosts file
          server.1=zk1.yuki.es:2888:3888
          server.2=zk2.yuki.es:2888:3888
          server.3=zk3.yuki.es:2888:3888
    
    - name: "Configure systemd service"
      copy:
        # src: ./conf/systemd/zookeper.service
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Zookeeper Daemon
          Documentation=http://zookeeper.apache.org
          Requires=network.target
          After=network.target

          [Service]    
          Type=forking
          WorkingDirectory=/opt/zookeeper
          User=zookeeper
          Group=zookeeper
          ExecStart=/opt/zookeeper/bin/zkServer.sh start /opt/zookeeper/conf/zoo.cfg
          ExecStop=/opt/zookeeper/bin/zkServer.sh stop /opt/zookeeper/conf/zoo.cfg
          ExecReload=/opt/zookeeper/bin/zkServer.sh restart /opt/zookeeper/conf/zoo.cfg
          TimeoutSec=30
          Restart=on-failure

          [Install]
          WantedBy=default.target

    - name: "systemctl daemon-reload"
      shell: systemctl daemon-reload

    - name: Start service zookeper and enable it
      service:
        name: zookeeper
        state: started
        enabled: yes

# latest kafka version
# wget https://downloads.apache.org/kafka/3.6.0/kafka_2.12-3.6.0.tgz