- name: Cambiar password de usuario yuki
  hosts: all
  tasks:
    - name: "Call bahul"
      ansible.builtin.uri: # Módulo de llamadas HTTP de ansible
        url: https://bahul.yuki.es/api/linuxYukiIncPass # Url de la llamada, si hay espacios hay que url encodearlos
        method: GET # Metodo que debamos definir
        headers:
          x-token: "{{ token }}" # Definimos los headers como si fuese un json, la variable token la pasamos con el parametro -e token="jdasbd" 
                                 # desde semaphore debemos meterlo en una array [ "-e", "token=efewfewf..."]
      register: "pass" # Nombre de la varibale donde queramos guardar el output

    - name: Cambiamos el password al usuario yuki
      shell:
        echo "yuki:{{ pass.json.body.pass }}"|chpasswd

    - name: "Send notification"
      ansible.builtin.uri: # Módulo de llamadas HTTP de ansible
        url: https://chat.googleapis.com/v1/spaces/AAAAlCHjbao/messages?key=...
        method: POST
        headers:
          Content-Type: "application/json; charset=UTF-8" # Importante en Google chat definir el tipo de contenido del body
        body_format: json # Le decimos al módulo de Ansible que el body lo parsee a json, de lo contrario mandara texto plano
        body: # En Google chat sí o sí la estructura del mensaje es {body: {text: "ewfewf"}}
          # Establecemos el mensage que queramos, se pueden usar variables de esta forma
          text: "*Executed on:* {{ ansible_hostname }}\n*Playbook executed:* {{ ansible_play_name }}\n" 