- name: Patch Multipath errors
  hosts: all
  tasks:
    - name: Add /etc/multipath.conf blacklist
      blockinfile:
        dest: /etc/multipath.conf
        block: |
          blacklist {
              device {
                  vendor "VMware"
                  product "Virtual disk"
              }
          }

    - name: Restart service multipath-tools service
      service:
        name: multipath-tools
        state: restarted