- name: "Actualizar Linux y reinciar si es necesario"
  become: yes
  hosts: all
  tasks:
    - name: Remove apt lock file
      block: # Usado como un try catch, primero hace el "block:" en caso de petar el block en alguna parte ejecuta el "rescue:"
        - name: "Try to remove lock file"
          file:
            state: absent
            path: "/var/lib/dpkg/lock"
      rescue:
        - name: "Print fail message to console"
          ansible.builtin.debug:
            msg: 'lock file probably didnt exist'

    - name: "Update apt-get repo and cache"
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
        upgrade: full

    - name: "Check if a reboot is needed for Debian and Ubuntu boxes"
      stat: 
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Reboot the Debian or Ubuntu server"
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 20
        reboot_timeout: 300
        post_reboot_delay: 20
        test_command: whoami
      when: reboot_required_file.stat.exists == true      