#! No está probado
- name: Instalar docker
  hosts: all
  become: yes # Ejecuta como root
  become_user: root
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:
    - name: Instalar dependencias
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Agregar clave gpg
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repo de docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Instala docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Asegurar que docker esta iniciado
      service:
        name: docker
        state: started
        enabled: yes

    - name: Agregar usuario a grupo docker
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items:
        - yuki
        - root
        - yuki
      
  handlers:
  - name: restart docker
    service: 
      name: docker 
      state: restarted

#Queda copiar daemon.json y reiniciar docker