- name: Patch Multipath errors
  become_method: sudo
  become: yes #Aunque el linter lo corrija es con yes
  hosts: all
  tasks:
    # Elimina los errores relacionados con el Multipath de los logs de las MV
    - name: Add /etc/multipath.conf blacklist
      blockinfile:
        dest: /etc/multipath.conf
        block: |
          blacklist {
              device {
                  vendor "VMware"
                  product "Virtual disk"
              }
          }

    - name: Restart service multipath-tools service
      service:
        name: multipath-tools
        state: restarted
