- name: Add ubuntu semaphore to AD
  hosts: localhost
  connection: local
  become: true
  tasks:
  
    - name: Define correct hostname if needed
      shell: if ! hostname | grep yuki.es ; then hostnamectl set-hostname $(hostname).yuki.es; fi
    
    # * UBUNTU 20.04
    - name: Set up repos
      blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
          deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"

    - name: Install multiple necessary packages
      apt: 
        pkg: 
          - realmd 
          - libnss-sss 
          - libpam-sss 
          - sssd 
          - sssd-tools 
          - adcli 
          - samba-common-bin
          - oddjob 
          - oddjob-mkhomedir 
          - packagekit
        update_cache: yes
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"

    - name: Start realmd
      service:
        name: sssd
        state: restarted
        enabled: yes
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"

    - name: Replace default no to yes
      replace:
        path: /usr/share/pam-configs/mkhomedir
        regexp: 'Default: no'
        replace: "Default: yes"
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"
    
    - name: Enable pam-auth module
      blockinfile:
        path: /etc/pam.d/common-session
        block: |
          session optional                        pam_mkhomedir.so
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"
    
    - name: Refresh pam-auth-update
      shell : pam-auth-update --force --enable mkhomedir && pam-auth-update --package
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"

    # * UBUNTU 22.04
    - name: Install multiple necessary packages
      apt: 
        pkg: 
          - sssd-ad 
          - sssd-tools
          - realmd
          - adcli 
        update_cache: yes
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '20.04'"
    
    - name: Enable mkhomedir module
      # From an http server on my pc y get the password by the curl and then pass it to realm join
      shell: pam-auth-update --enable mkhomedir
      when: "'{{ ansible_distribution }}' == 'Ubuntu' and '{{ ansible_distribution_version }}': '22.04'"

    # * ALL
    - name: Join yuki domain
      # From an http server on my pc y get the password by the curl and then pass it to realm join
      shell: curl http://192.168.1.57:8000 | realm join -U amorell yuki.es
      
    - name: Allow AD users in LinuxAdmins group to log in
      shell : realm deny --all && realm permit -g 'LinuxAdmins'

    - name: Add to sudoers LinuxAdmins group
      blockinfile:
        path: /etc/sudoers.d/domain_admins
        create: yes
        block: |
          %linuxadmins@yuki.es     ALL=(ALL)   ALL

    - name: Restart sssd auth provider
      service:
        name: sssd
        state: restarted
        enabled: yes