- name: Instalar agente de zabbix2
  hosts: all
  become: yes
  become_user: root
  vars:
    package_names:
      - docker

  tasks:
    - name: Descargar repo zabbix-agent2 ubuntu 22.04
      ansible.builtin.shell: /usr/bin/wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3%2Bubuntu22.04_all.deb -O ~/zabbix-agent2.deb
      when: ansible_facts['lsb']['release'] == "22.04"

    - name: Descargar repo zabbix-agent2 ubuntu 20.04
      ansible.builtin.shell: /usr/bin/wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb -O ~/zabbix-agent2.deb
      when: ansible_facts['lsb']['release'] == "20.04"

    - name: Descargar repo zabbix-agent2 ubuntu 18.04
      ansible.builtin.shell: /usr/bin/wget "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu18.04_all.deb" -O ~/zabbix-agent2.deb
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Instalar repo zabbix-agent2
      shell: /usr/bin/dpkg -i ~/zabbix-agent2.deb
      args:
        executable: /bin/bash

    - name: Apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Instalar zabbix-agent2
      shell: /usr/bin/apt-get install -y zabbix-agent2 
      args:
        executable: /bin/bash

    - name: Firewall zabbix-agent2
      shell: /usr/sbin/ufw allow proto tcp from 192.168.1.193 to any port 10050 comment "zabbix-agent"
      args:
        executable: /bin/bash

    - name: Definimos el Server en la configuración
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^Server=.*
        insertafter: ^# Server=
        line: Server=192.168.1.193

    - name: Definimos el ServerActive en la configuración
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^ServerActive=.*
        insertafter: ^# ServerActive=
        line: ServerActive=192.168.1.193

    - name: Definimos el Hostname en la configuración
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        regexp: ^Hostname=.*
        insertafter: ^# Hostname=
        line: Hostname={{ ansible_hostname }}
    
    - name: Reiniciar agente
      shell: /bin/systemctl restart zabbix-agent2.service
      args:
        executable: /bin/bash

    - name: Estado del agente
      shell: /usr/sbin/service zabbix-agent2 status
      args:
        executable: /bin/bash
      register: output
    - debug: msg="{{ output.stdout }}"

    - name: "Comprobamos si docker esta instalado"
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check

    - name: Add zabbix to docker group
      ansible.builtin.command: /usr/sbin/usermod -aG docker zabbix
      when: package_check is succeeded

    - name: Reiniciar agente tras agregarlo a docker
      shell: /bin/systemctl restart zabbix-agent2.service
      args:
        executable: /bin/bash